### PR TITLE
Fix aaaallll the things 🎉

### PR DESCRIPTION
**Pull request by timbremer**
Pass args as int, implement more switch cases, correct var allocation

### CODE REVIEW

**Comment by JKortmann** [comment]
think wont work

**Comment by JKortmann** [comment]
lül

**Comment by lscheibel** [comment]
shouldnt anyway

**Comment by timbremer** [comment]
prolly no but ¯\_(ツ)_/¯

**Comment by lscheibel** [comment]
I made better #11 ! is muchbetter

**Comment by timbremer** [comment]
Nonononono https://github.com/dimw/ws18-webdev1-calc/pull/7/commits/52dc9622a33ba3da913764479bb5f321200d606c

**Pull request merged**
